install_taxcalc_version: 0.6.8
compare_ogusa_version: 0.5.5
compare_taxcalc_version: 0.6.6
diff: True
numpy_version: 1.10
# Path to reforms.json relative to Python/regression
reform_specs_json: reforms.json

# Just check if you can download and install
# the specs above and import * from run_reforms.py
dry_run_imports_installs_only: True 
