package:
  name: ogusa
  version: {{ environ.get("GIT_DESCRIBE_TAG", "NOTAG")}}

requirements:
  build:
    - setuptools
    - scipy
    - matplotlib
    - numpy
    - pandas
    - pytest
    - python

  run:
    - setuptools
    - scipy
    - taxcalc
    - matplotlib
    - numpy
    - pandas
    - pytest
    - python 

about:
  home: https://github.com/open-source-economics/OG-USA/
